[package]
name = "meme-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
arboard = "2"
memeinator = { path = "../memeinator" }
anyhow = "1.0.47"
image = "0.23"
